name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Set up Docker Buildx for multi-platform support and caching
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and push the Docker image Api Gateway
      - name: Build and push Api Gateway image
        uses: docker/build-push-action@v6
        with:
          context: ./api-gateway
          file: api-gateway/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
            ${{ secrets.DOCKER_USERNAME }}/api-gateway:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/api-gateway:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/api-gateway:buildcache,mode=max

      # Build and push the Docker image Admin Service
      - name: Build and push Admin Service image
        uses: docker/build-push-action@v6
        with:
          context: ./admin-service
          file: admin-service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/admin-service:latest
            ${{ secrets.DOCKER_USERNAME }}/admin-service:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/admin-service:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/admin-service:buildcache,mode=max

      # Build and push the Docker image Appointment Service
      - name: Build and push Appointment Service image
        uses: docker/build-push-action@v6
        with:
          context: ./appointment-service
          file: appointment-service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/appointment-service:latest
            ${{ secrets.DOCKER_USERNAME }}/appointment-service:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/appointment-service:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/appointment-service:buildcache,mode=max

      # Build and push the Docker image Auth Service
      - name: Build and push Auth Service image
        uses: docker/build-push-action@v6
        with:
          context: ./auth-service
          file: auth-service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/auth-service:latest
            ${{ secrets.DOCKER_USERNAME }}/auth-service:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/auth-service:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/auth-service:buildcache,mode=max

      # Verify image built and pushed
      - name: Verify pushed image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest

      - name: Verify Admin Service image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/admin-service:latest

#      - name:  Analyze with SonarQube
#        uses: SonarSource/sonarqube-scan-action@7295e71c9583053f5bf40e9d4068a0c974603ec8
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on SonarQube, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
#          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
#        with:
#          # Additional arguments for the sonarcloud scanner
#          args:
#            # Unique key of your project. You can find it in SonarQube > [my project] > Project Information (top-right menu)
#            # mandatory
#            -Dsonar.projectKey=
#            # Comma-separated paths to directories containing main source files.
#            #-Dsonar.sources= # optional, default is project base directory
#            # When you need the analysis to take place in a directory other than the one from which it was launched
#            #-Dsonar.projectBaseDir= # optional, default is .
#            # Comma-separated paths to directories containing test source files.
#            #-Dsonar.tests= # optional. For more info about Code Coverage, please refer to https://docs.sonarcloud.io/enriching/test-coverage/overview/
#          # Adds more detail to both client and server-side analysis logs, activating DEBUG mode for the scanner, and adding client-side environment variables and system properties to the server-side log of analysis report processing.
#          #-Dsonar.verbose= # optional, default is false
