name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Set up Docker Buildx for multi-platform support and caching
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and push the Docker image
      - name: Build and push Api Gateway image
        uses: docker/build-push-action@v6
        with:
          context: ./api-gateway
          file: api-gateway/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
            ${{ secrets.DOCKER_USERNAME }}/api-gateway:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/api-gateway:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/api-gateway:buildcache,mode=max

      # Build and push the Docker image
      - name: Build and push Admin Service image
        uses: docker/build-push-action@v6
        with:
          context: ./admin-service
          file: admin-service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/admin-service:latest
            ${{ secrets.DOCKER_USERNAME }}/admin-service:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/admin-service:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/admin-service:buildcache,mode=max

      # Verify image built and pushed
      - name: Verify pushed image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest

      - name: Verify Admin Service image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/admin-service:latest